### PR TITLE
Fix incorrect selector layer when using a serial of sub selectors

### PR DESCRIPTION
**Pull request by ko1in1u**
This change is [Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/17)

### CODE REVIEW

**Review by eric100lin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/17)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ko1in1u)

___
*[`snippet_uiautomator/byselector.py` line 52 at r2](https://reviewable.io/reviews/google/snippet-uiautomator/17#-NeCYIuq3P-E-YtKUbYy:-NeCYIuq3P-E-YtKUbYz:bq91qow) ([raw file](https://github.com/google/snippet-uiautomator/blob/104d020b41aa6a0ca60d52b4873118a3e7c7cf5a/snippet_uiautomator/byselector.py#L52)):*
> ```Python
>       if key in self.SUBSELECTOR:
>         return self._find_bottom_selector(d[key])
>     return d
> ```

Got the following error in g3:
```
  in _find_bottom_selector: bad return type [bad-return-type]
           Expected: Mapping[str, Union[bool, int, str]]
  Actually returned: Mapping[str, Mapping[str, Union[Mapping[str, Union[bool, int, str]], bool, int, str, Mapping]]]
```

**Comment by ko1in1u** [comment]
> > _[Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/17)_ status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ko1in1u)
> 
> _[`snippet_uiautomator/byselector.py` line 52 at r2](https://reviewable.io/reviews/google/snippet-uiautomator/17#-NeCYIuq3P-E-YtKUbYy:-NeCYIuq3P-E-YtKUbYz:bq91qow) ([raw file](https://github.com/google/snippet-uiautomator/blob/104d020b41aa6a0ca60d52b4873118a3e7c7cf5a/snippet_uiautomator/byselector.py#L52)):_
> 
> > ```python
> >       if key in self.SUBSELECTOR:
> >         return self._find_bottom_selector(d[key])
> >     return d
> > ```
> 
> Got the following error in g3:
> 
> ```
>   in _find_bottom_selector: bad return type [bad-return-type]
>            Expected: Mapping[str, Union[bool, int, str]]
>   Actually returned: Mapping[str, Mapping[str, Union[Mapping[str, Union[bool, int, str]], bool, int, str, Mapping]]]
> ```

Update the correct type

**Review by eric100lin — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/17#-:-NeCbUy7DGHe_SqyBUux:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @ko1in1u)

**Review by eric100lin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/17)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[`snippet_uiautomator/byselector.py` line 45 at r3](https://reviewable.io/reviews/google/snippet-uiautomator/17#-NeCd5Ns8Y9sKXd1ja4t:-NeCd5Ns8Y9sKXd1ja4u:b-1jfjyq) ([raw file](https://github.com/google/snippet-uiautomator/blob/ecfa88a249ab0b61c4526f7ccf46aa562b1d82bf/snippet_uiautomator/byselector.py#L45)):*
> ```Python
>     """Converts the keyword arguments to selector type."""
>     self._selector = dict(kwargs)
>     self._bottom = self._selector
> ```

Just curious, if we always copy with only SUBSELECTOR in `self._bottom`.
Why not just filter SUBSELECTOR here:
```
self._bottom = self._find_bottom_selector(self._selector)
```

so we don't need to disable protected-access lint, WDYT?



_Code quote:_
```Python
self._bottom = self._selector
```

**Comment by ko1in1u** [comment]
> > _[Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/17)_ status: 0 of 3 files reviewed, 1 unresolved discussion
> 
> _[`snippet_uiautomator/byselector.py` line 45 at r3](https://reviewable.io/reviews/google/snippet-uiautomator/17#-NeCd5Ns8Y9sKXd1ja4t:-NeCd5Ns8Y9sKXd1ja4u:b-1jfjyq) ([raw file](https://github.com/google/snippet-uiautomator/blob/ecfa88a249ab0b61c4526f7ccf46aa562b1d82bf/snippet_uiautomator/byselector.py#L45)):_
> 
> > ```python
> >     """Converts the keyword arguments to selector type."""
> >     self._selector = dict(kwargs)
> >     self._bottom = self._selector
> > ```
> 
> Just curious, if we always copy with only SUBSELECTOR in `self._bottom`. Why not just filter SUBSELECTOR here:
> 
> ```
> self._bottom = self._find_bottom_selector(self._selector)
> ```
> 
> so we don't need to disable protected-access lint, WDYT?
> 
> _Code quote:_
> 
> ```python
> self._bottom = self._selector
> ```

We only need to know the object of the innermost dictionary object when copying. Not sure if we need to check in the constructor but I'm okay to move if needed.

**Pull request merged**
