### PR TITLE
Raise an error when uiautomation service has already registered

### PR DESCRIPTION
**Pull request by ko1in1u**
This change is [Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/21)

### CODE REVIEW

**Review by eric100lin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/21)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ko1in1u)

___
*[`snippet_uiautomator/uiautomator.py` line 141 at r1](https://reviewable.io/reviews/google/snippet-uiautomator/21#-NeMUM_X1qSSXiZ2gMZy:-NeMUM_X1qSSXiZ2gMZz:b-2sj45e) ([raw file](https://github.com/google/snippet-uiautomator/blob/38154473151deb38bb58cf6fc3762d7237ce116f/snippet_uiautomator/uiautomator.py#L141)):*
> ```Python
>         self._device.services.snippets.get_snippet_client(self._service)
>         is not None
>     ):
> ```

Are these lines changes needed?



_Code quote:_
```Python
    if (
        self._device.services.snippets.get_snippet_client(self._service)
        is not None
    ):
```
___
*[`snippet_uiautomator/uiautomator.py` line 150 at r1](https://reviewable.io/reviews/google/snippet-uiautomator/21#-NeMUmLT5-cFfsxr3IiZ:-NeMUmLT5-cFfsxr3Ii_:bryedvv) ([raw file](https://github.com/google/snippet-uiautomator/blob/38154473151deb38bb58cf6fc3762d7237ce116f/snippet_uiautomator/uiautomator.py#L150)):*
> ```Python
>       raise errors.ConfigurationError(errors.ERROR_WHEN_PACKAGE_NAME_MISSING)
> 
>     self._device.adb.logcat(['-c'])
> ```

Can we use logcat pubsub or timestamp to match instead of cleaning logcat buffer?



_Code quote:_
```Python
self._device.adb.logcat(['-c'])
```

**Comment by ko1in1u** [comment]
> > _[Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/21)_ status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ko1in1u)
> 
> _[`snippet_uiautomator/uiautomator.py` line 141 at r1](https://reviewable.io/reviews/google/snippet-uiautomator/21#-NeMUM_X1qSSXiZ2gMZy:-NeMUM_X1qSSXiZ2gMZz:b-2sj45e) ([raw file](https://github.com/google/snippet-uiautomator/blob/38154473151deb38bb58cf6fc3762d7237ce116f/snippet_uiautomator/uiautomator.py#L141)):_
> 
> > ```python
> >         self._device.services.snippets.get_snippet_client(self._service)
> >         is not None
> >     ):
> > ```
> 
> Are these lines changes needed?

This is changed by formatter since its original line is over 80.


> _Code quote:_
> 
> ```python
>     if (
>         self._device.services.snippets.get_snippet_client(self._service)
>         is not None
>     ):
> ```
> 
> _[`snippet_uiautomator/uiautomator.py` line 150 at r1](https://reviewable.io/reviews/google/snippet-uiautomator/21#-NeMUmLT5-cFfsxr3IiZ:-NeMUmLT5-cFfsxr3Ii_:bryedvv) ([raw file](https://github.com/google/snippet-uiautomator/blob/38154473151deb38bb58cf6fc3762d7237ce116f/snippet_uiautomator/uiautomator.py#L150)):_
> 
> > ```python
> >       raise errors.ConfigurationError(errors.ERROR_WHEN_PACKAGE_NAME_MISSING)
> > 
> >     self._device.adb.logcat(['-c'])
> > ```
> 
> Can we use logcat pubsub or timestamp to match instead of cleaning logcat buffer?
> 
> _Code quote:_
> 
> ```python
> self._device.adb.logcat(['-c'])
> ```

Logcat pubsub service will be too complicated and it is not a public service, I'll come up with matching timestamp.

**Comment by ko1in1u** [comment]
Local test to launch when uiautomator is registered by other app.

```
uiautomator.load_uiautomator_service(ad)
ERROR:root:[AndroidDevice|21061FDEE006T5] Error occurred trying to start and connect to the snippet server of com.google.android.mobly.snippet.uiautomator.
Traceback (most recent call last):
  File "/usr/local/google/home/kolinlu/.local/lib/python3.11/site-packages/snippet_uiautomator/uiautomator.py", line 163, in _load_snippet
    self._device.load_snippet(
  File "/usr/local/google/home/kolinlu/.local/lib/python3.11/site-packages/mobly/controllers/android_device.py", line 929, in load_snippet
    self.services.snippets.add_snippet_client(name, package)
  File "/usr/local/google/home/kolinlu/.local/lib/python3.11/site-packages/mobly/controllers/android_device_lib/services/snippet_management_service.py", line 83, in add_snippet_client
    client.initialize()
  File "/usr/local/google/home/kolinlu/.local/lib/python3.11/site-packages/mobly/snippet/client_base.py", line 128, in initialize
    self.start_server()
  File "/usr/local/google/home/kolinlu/.local/lib/python3.11/site-packages/mobly/controllers/android_device_lib/snippet_client_v2.py", line 248, in start_server
    raise errors.ServerStartProtocolError(self._device, line)
mobly.snippet.errors.ServerStartProtocolError: <AndroidDevice|21061FDEE006T5> INSTRUMENTATION_RESULT: shortMsg=Process crashed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/google/home/kolinlu/.local/lib/python3.11/site-packages/snippet_uiautomator/uiautomator.py", line 274, in load_uiautomator_service
    ad.services.register(
  File "/usr/local/google/home/kolinlu/.local/lib/python3.11/site-packages/mobly/controllers/android_device_lib/service_manager.py", line 85, in register
    service_obj.start()
  File "/usr/local/google/home/kolinlu/.local/lib/python3.11/site-packages/snippet_uiautomator/uiautomator.py", line 228, in start
    self._load_snippet()
  File "/usr/local/google/home/kolinlu/.local/lib/python3.11/site-packages/snippet_uiautomator/uiautomator.py", line 183, in _load_snippet
    raise errors.UiAutomationServiceAlreadyRegisteredError(
snippet_uiautomator.errors.UiAutomationServiceAlreadyRegisteredError: [AndroidDevice|21061FDEE006T5] UiAutomation service has been registered by another app. Please stop the app to release the service.
```

**Review by eric100lin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/21)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ko1in1u)

___
*[`snippet_uiautomator/uiautomator.py` line 150 at r1](https://reviewable.io/reviews/google/snippet-uiautomator/21#-NeMUmLT5-cFfsxr3IiZ:-NePBL-s3CVkgoMWfhrq:bxe6us5) ([raw file](https://github.com/google/snippet-uiautomator/blob/38154473151deb38bb58cf6fc3762d7237ce116f/snippet_uiautomator/uiautomator.py#L150)):*
<details><summary><i>Previously, ko1in1u (Kolin Lu) wrote…</i></summary><blockquote>

Logcat pubsub service will be too complicated and it is not a public service, I'll come up with matching timestamp.
</blockquote></details>

Consider to add unit tests, ref: [PR#22](https://github.com/google/snippet-uiautomator/pull/22).

**Review by eric100lin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/21)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @ko1in1u)

___
*[`snippet_uiautomator/uiautomator.py` line 145 at r2](https://reviewable.io/reviews/google/snippet-uiautomator/21#-NePEpZxDzrYHamle1mp:-NePEpZyABI4Yd72Zbaf:b4ga5q8) ([raw file](https://github.com/google/snippet-uiautomator/blob/c16d9200336a1d1a816a3b98812dab72eb96a03a/snippet_uiautomator/uiautomator.py#L145)):*
> ```Python
>         self._device.services.snippets.get_snippet_client(self._service)
>         is not None
>     ):
> ```

Consider to break the long expression by introducing temp variable:
```
snippet_manager = self._device.services.snippets  
if snippet_manager.get_snippet_client(self.\service) is not None:
```



_Code quote:_
```Python
    if (
        self._device.services.snippets.get_snippet_client(self._service)
        is not None
    ):
```
___
*[`snippet_uiautomator/uiautomator.py` line 156 at r2](https://reviewable.io/reviews/google/snippet-uiautomator/21#-NePGBgg1C09Yk0WRZdc:-NePGBgg1C09Yk0WRZdd:b9y31z) ([raw file](https://github.com/google/snippet-uiautomator/blob/c16d9200336a1d1a816a3b98812dab72eb96a03a/snippet_uiautomator/uiautomator.py#L156)):*
> ```Python
>     start_time = datetime.datetime.strptime(
>         (
>             self._device.adb.shell(['date', f'+"{_LOGCAT_TIME_FORMAT}"'])
> ```

There is a [logline_timestamp_comparator](https://github.com/google/mobly/blob/539a442ed0a396ceec1dfd692f452ddf1380a872/mobly/controllers/android_device_lib/services/logcat.py#L94) in Mobly repo.
The logcat logs are streaming from device to a host file in timestamp format.
I think we can get the last line as start/end time.



_Code quote:_
```Python
'date', f'+"{_LOGCAT_TIME_FORMAT}"'
```

**Comment by ko1in1u** [comment]
> > _[Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/21)_ status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @ko1in1u)
> 
> _[`snippet_uiautomator/uiautomator.py` line 145 at r2](https://reviewable.io/reviews/google/snippet-uiautomator/21#-NePEpZxDzrYHamle1mp:-NePEpZyABI4Yd72Zbaf:b4ga5q8) ([raw file](https://github.com/google/snippet-uiautomator/blob/c16d9200336a1d1a816a3b98812dab72eb96a03a/snippet_uiautomator/uiautomator.py#L145)):_
> 
> > ```python
> >         self._device.services.snippets.get_snippet_client(self._service)
> >         is not None
> >     ):
> > ```
> 
> Consider to break the long expression by introducing temp variable:
> 
> ```
> snippet_manager = self._device.services.snippets  
> if snippet_manager.get_snippet_client(self.\service) is not None:
> ```
> 
> _Code quote:_
> 
> ```python
>     if (
>         self._device.services.snippets.get_snippet_client(self._service)
>         is not None
>     ):
> ```
> 
> _[`snippet_uiautomator/uiautomator.py` line 156 at r2](https://reviewable.io/reviews/google/snippet-uiautomator/21#-NePGBgg1C09Yk0WRZdc:-NePGBgg1C09Yk0WRZdd:b9y31z) ([raw file](https://github.com/google/snippet-uiautomator/blob/c16d9200336a1d1a816a3b98812dab72eb96a03a/snippet_uiautomator/uiautomator.py#L156)):_
> 
> > ```python
> >     start_time = datetime.datetime.strptime(
> >         (
> >             self._device.adb.shell(['date', f'+"{_LOGCAT_TIME_FORMAT}"'])
> > ```
> 
> There is a [logline_timestamp_comparator](https://github.com/google/mobly/blob/539a442ed0a396ceec1dfd692f452ddf1380a872/mobly/controllers/android_device_lib/services/logcat.py#L94) in Mobly repo. The logcat logs are streaming from device to a host file in timestamp format. I think we can get the last line as start/end time.
> 
> _Code quote:_
> 
> ```python
> 'date', f'+"{_LOGCAT_TIME_FORMAT}"'
> ```

Done

**Review by eric100lin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/21)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @ko1in1u)

___
*[`snippet_uiautomator/utils.py` line 80 at r3](https://reviewable.io/reviews/google/snippet-uiautomator/21#-NeaQeS03upHYNedtDqX:-NeaY-8O-aQHf-7MzW6-:b-kvpu9e) ([raw file](https://github.com/google/snippet-uiautomator/blob/90d8234fb92c0b633342ce88cf89d5cc6199173c/snippet_uiautomator/utils.py#L80)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

If I understand correctly, here we want to extract the timestamp of the log line ".*UiAutomationService.*registered".
Consider to have one `re.match` with [sub group](https://docs.python.org/3/library/re.html#re.Match.group):
ex:
```
REGEX_LOGCAT_TIMESTAMP = r'\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}'
REGEX_UIA_SERVICE_ALREADY_REGISTERED = r'.*UiAutomationService.*registered'


  logcat = ad.adb.logcat(['-d', '-s', 'AndroidRuntime:E']).decode()
  match = re.match(
      f'({REGEX_LOGCAT_TIMESTAMP}){REGEX_UIA_SERVICE_ALREADY_REGISTERED}',
      last_line,
  )
  if not match:
    return False

  error_time = match.group(1)
  return mobly_logger.logline_timestamp_comparator(error_time, start_time) > -1
```
</blockquote></details>

To match the latest error,
you might need to replace `re.match` by `re.findall` in the example and use `error_time = match[-1][0]`.

**Review by eric100lin — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 3 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/21#-:-Neqm0d-BP9Pi8HcESBD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ko1in1u)

**Pull request merged**
