### PR TITLE
Migrate -jre flavor of Guava to -android flavor

### PR DESCRIPTION
**Pull request by ko1in1u**
See https://github.com/google/guava/wiki/ReleasePolicy#flavors

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/47)

### CODE REVIEW

**Review by eric100lin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/47)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @ko1in1u)

___
*[`snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/UiDeviceSnippet.java` line 71 at r1](https://reviewable.io/reviews/google/snippet-uiautomator/47#-NyJk2Ah6zCPzH20webw:-NyJk2Ah6zCPzH20webx:b-w07ujk) ([raw file](https://github.com/google/snippet-uiautomator/blob/5e33dddb272121a290b4285c63e57a63da931127/snippet_uiautomator/android/app/src/main/java/com/google/android/mobly/snippet/uiautomator/UiDeviceSnippet.java#L71)):*
> ```Java
>     return uiDevice.findObjects(selector.toBySelector()).stream()
>         .map(Info::getUiObject2Info)
>         .collect(toImmutableList());
> ```

Could you explain why we should replace all instances of `stream.collect(toImmutableList())` with `ImmutableList.copyOf(stream.iterator())`? The Java practice documentation (go/java-practices/streams#iterator) strongly discourages the use of `Stream.iterator()`.



_Code quote:_
```Java
.collect(toImmutableList())
```

**Comment by ko1in1u** [comment]
> Could you explain why we should replace all instances of `stream.collect(toImmutableList())` with `ImmutableList.copyOf(stream.iterator())`? The Java practice documentation (go/java-practices/streams#iterator) strongly discourages the use of `Stream.iterator()`.

It is bc the -android flavor of Guava lacks a public ImmutableList.toImmutableList symbol.  Guava's release policy guides that users should target the -android flavor to be compatible with either (see https://github.com/google/guava/wiki/ReleasePolicy#flavors).

I'll check another way to replace Stream.iterator(). Thank you for the information.

**Review by eric100lin — COMMENTED** [review]
Would you consider upgrade the Guava lib to 33.2.0-android?
https://github.com/google/guava/releases/tag/v33.2.0
Fortunately, this version made `ImmutableList.toImmutableList()` available in `guava-android`.

> *[Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/47#-:-NyOE5iv9d-52jcFVHt8:b-acyben)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @ko1in1u)

**Comment by ko1in1u** [comment]
> Would you consider upgrade the Guava lib to 33.2.0-android? https://github.com/google/guava/releases/tag/v33.2.0 Fortunately, this version made `ImmutableList.toImmutableList()` available in `guava-android`.

That is great catch! Upgraded to 33.2.0 and verified internally that `ImmutableList.toImmutableList()` works.
Thank you!

**Review by eric100lin — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/47#-:-NyPKUEX7Tw8R10tDvh5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ko1in1u)

**Pull request merged**
