### PR TITLE
Fix Selector being overwritten when creating an instance of child UiObject2

### PR DESCRIPTION
**Pull request by ko1in1u**
This change is [Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/6)

### CODE REVIEW

**Review by eric100lin — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/6)* status: all files reviewed, 1 unresolved discussion (waiting on @ko1in1u)

___
*[`snippet_uiautomator/uiobject2.py` line 465 at r1](https://reviewable.io/reviews/google/snippet-uiautomator/6#-Ne3k-0CDtqMgbslDH32:-Ne3k-0CDtqMgbslDH33:btto31k) ([raw file](https://github.com/google/snippet-uiautomator/blob/fdba0332edbfbc0a9a4925bd2eb6a1871075c526/snippet_uiautomator/uiobject2.py#L465)):*
> ```Python
>     selector = self._selector.copy()
>     selector.append('parent')
>     return UiObject2(self._ui, selector, self._raise_error)
> ```

I think we can use `_create_instance` here: `return self._create_instance('parent')`



_Code quote:_
```Python
    selector = self._selector.copy()
    selector.append('parent')
    return UiObject2(self._ui, selector, self._raise_error)
```

**Comment by ko1in1u** [comment]
> > Reviewed 3 of 3 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/6)_ status: all files reviewed, 1 unresolved discussion (waiting on @ko1in1u)
> 
> _[`snippet_uiautomator/uiobject2.py` line 465 at r1](https://reviewable.io/reviews/google/snippet-uiautomator/6#-Ne3k-0CDtqMgbslDH32:-Ne3k-0CDtqMgbslDH33:btto31k) ([raw file](https://github.com/google/snippet-uiautomator/blob/fdba0332edbfbc0a9a4925bd2eb6a1871075c526/snippet_uiautomator/uiobject2.py#L465)):_
> 
> > ```python
> >     selector = self._selector.copy()
> >     selector.append('parent')
> >     return UiObject2(self._ui, selector, self._raise_error)
> > ```
> 
> I think we can use `_create_instance` here: `return self._create_instance('parent')`
> 
> _Code quote:_
> 
> ```python
>     selector = self._selector.copy()
>     selector.append('parent')
>     return UiObject2(self._ui, selector, self._raise_error)
> ```

Done.

**Review by eric100lin — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/6#-:-Ne3ocg5BJYyN-MY3tA8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ko1in1u)

**Review by eric100lin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/snippet-uiautomator/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ko1in1u)

**Pull request merged**
